<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\lib\Debug\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\lib\Release\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>


  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="ECommerce.Domain">
      <HintPath>..\lib\Debug\ECommerce.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Reference Include="ECommerce.Domain">
      <HintPath>..\lib\Release\ECommerce.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="ECommerce.ServiceAbstraction">
      <HintPath>..\lib\Debug\ECommerce.ServiceAbstraction.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Reference Include="ECommerce.ServiceAbstraction">
      <HintPath>..\lib\Release\ECommerce.ServiceAbstraction.dll</HintPath>
    </Reference>
  </ItemGroup>


</Project>
