version: "3.7"

services:
   app:
       container_name: mysql
       image: mysql/mysql-server:5.7
       ports:
        - 3307:3306
       environment:
          MYSQL_ROOT_PASSWORD: MyNewPass  
       volumes:
         -  ./data:/var/lib/mysql
        
      
      
           